In [3]:
import numpy as np
list1=["1","2","3","4"]
array_list = np.array(object = list1)

Q1

In [5]:

type(array_list)

numpy.ndarray

In [7]:
array_list

array(['1', '2', '3', '4'], dtype='<U1')

In [6]:
type(list1)

list

Q2

In [8]:
# Write a code to print the data type of each and every element of both the variables list_ and 
# arra_list.


for i in list1:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3

In [10]:
array_list1 = np.array(object = list1, dtype = int)

type(array_list1)

numpy.ndarray

In [11]:
type(list1)

list

In [12]:
for i  in list1:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list1:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q4

In [14]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# (i)	 shape

# (ii) size

num_array.shape

(2, 3)

In [16]:
num_array.size

6

Q5

In [19]:
# Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
# creation function


np.zeros(9).reshape(3,3)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6

In [21]:
# . Create an identity matrix of shape (5,5) using numpy functions?

np.eye(5)



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])